"""Prompt construction for the Generator and Refiner roles.

===========================================================================
CRITICAL — WHAT THE GENERATOR MUST NOT RECEIVE
===========================================================================
The SALT decision tree, the seven-input derivation table, and the R1 rule text
are **deliberately absent from the generator prompt**. Do not add them.

Rationale, learned the expensive way on Assignment #4 of this course: when the
generator is handed the exact rule it is about to be checked against, it
self-censors. Every item passes on the first attempt, the evaluator logs
"clean" for all of them, and the pipeline produces zero evidence that the
evaluator does anything at all — the graded artifact becomes an empty log. On
A#4 the fix was moving the consistency rules out of the generator prompt and
leaving them only in the critic; the same separation applies here and is the
reason this pipeline can show real catches.

There is a second, non-tactical reason. The generator is standing in for a human
content author, and a human content author authoring a casualty row does exactly
what this prompt asks: they picture the injury, type plausible vitals, and
declare the category their clinical intuition suggests. They do not run the
decision tree in their head field by field. The bug this pipeline is built to
catch — a row whose declared category disagrees with its own numbers — is
*generated by* that intuitive process. Giving the generator the tree would
prevent the bug and thereby prevent the demonstration.

===========================================================================
WHAT THE REFINER MUST NOT RECEIVE
===========================================================================
The refiner gets the failing item and the violation list (code, rule,
gdd_source, detail). It does **not** get the derived category, and no violation
detail ever says "set the category to Red". The refiner has to reconcile the
row's own numbers against the stated rule itself.

If the refiner were simply told the answer, the loop would prove only that the
pipeline can copy a string from the evaluator into the output — it would not
show a correction being reasoned. It also matters for the escalation path: an
item the refiner genuinely cannot reconcile is the item the circuit breaker is
supposed to trip on, and spoon-feeding the answer would make every item fixable
and the breaker unreachable.

The refiner also does not receive the request brief, and that boundary has a
consequence worth naming rather than discovering later. Some findings can only
be settled from the brief: `severe_tbi_expectant`'s brief says the casualty
"cannot be saved with the resources actually available", which is exactly the
fact that decides its Immediate-versus-Expectant split. Withholding it means
that item is unresolvable by construction — which is the escalation this
pipeline is built to demonstrate, but it is a *design choice about the
information set*, not a mystery about the rule. Widening the refiner's inputs to
include the brief is the obvious next experiment; it is deliberately not done
here, because the run would then have no item the breaker could trip on.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

from .evaluator import redact_violations
from .requests import ArchetypeRequest
from .schema import ArchetypeRow, GeneratedArchetype, SaltCategory, TriageIntent, Violation

KB_DIR = Path(__file__).resolve().parent.parent / "knowledge_base"
EXEMPLAR_CSV = KB_DIR / "DT_CasualtyArchetypes.exemplar.csv"
SCHEMA_DOC = KB_DIR / "casualty-archetype-schema.md"


def load_exemplar_csv_text() -> str:
    """The real DataTable source: header + the single hand-authored row.

    Grounding the generator in the actual file means the output shape is copied
    from something that already imports into Unreal, rather than described in
    prose and hopefully reproduced.
    """
    return EXEMPLAR_CSV.read_text(encoding="utf-8").strip()


def load_exemplar_row_names() -> set[str]:
    """The row keys already present in the live `DT_CasualtyArchetypes`.

    Not a prompt input — it lives here because this module owns the exemplar
    file path. `run_pipeline` seeds the evaluator's `seen_names` with it so
    `R4_DUPLICATE_NAME` can see a collision with the row that already exists,
    not just with rows generated earlier in the same run. Without the seed the
    rule is structurally blind to the one collision that actually costs
    something: Unreal keys DataTable rows by `Name`, so a generated row reusing
    an existing key silently overwrites the hand-authored casualty on import.
    """
    with EXEMPLAR_CSV.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return {
            row["Name"].strip()
            for row in reader
            if row.get("Name") and row["Name"].strip()
        }


def load_field_group_excerpt() -> str:
    """The Group 1..7 field specification from the schema decision record.

    Sliced live out of `knowledge_base/casualty-archetype-schema.md` rather than
    restated here, so the prompt cannot drift from the copied source document.
    The slice runs from the first field group to the type-restriction notes,
    which is exactly the part that defines what each column means.
    """
    text = SCHEMA_DOC.read_text(encoding="utf-8")
    start_marker = "### Group 1 —"
    end_marker = "### Type-restriction notes"
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start == -1 or end == -1 or end <= start:
        raise ValueError(
            "Could not locate the Group 1..7 field specification in "
            f"{SCHEMA_DOC.name}. The knowledge-base copy has changed shape; the "
            "prompt builder must be updated to match rather than silently "
            "sending an empty schema section."
        )
    return text[start:end].strip()


def _type_name(annotation: object) -> str:
    """Render a field annotation as a short JSON-ish type name for the prompt."""
    if annotation is bool:
        return "boolean"
    if annotation is float:
        return "number"
    if annotation is int:
        return "integer"
    if annotation is str:
        return "string"
    if annotation is SaltCategory:
        return "one of " + " | ".join(f'"{c.value}"' for c in SaltCategory)
    return getattr(annotation, "__name__", str(annotation))


def json_shape() -> str:
    """The exact JSON object the roles must return, generated from the models.

    Derived from the pydantic models rather than hand-written, so the prompt and
    the validator can never disagree about the field list.
    """
    row_fields = {
        name: _type_name(f.annotation) for name, f in ArchetypeRow.model_fields.items()
    }
    intent_fields = {
        name: _type_name(f.annotation) for name, f in TriageIntent.model_fields.items()
    }
    shape = {"row": row_fields, "triage_intent": intent_fields}
    return json.dumps(shape, indent=2)


_OUTPUT_CONTRACT = """\
Return ONE JSON object and nothing else. No prose before or after, no markdown
code fence, no commentary. It must have exactly these two keys, with exactly
these fields and no extra fields:

{shape}

Field notes:
- "Name" is the DataTable row key. Use the form Casualty_<Descriptor> — letters,
  digits and underscores only, e.g. Casualty_IED_LegHemorrhage_T1.
- "CasualtyCharacterAssetPath" must be an Unreal content path starting with
  /Game/. If no specific art asset is known for this casualty, point it at
  /Game/GoldenHour/Characters/CasualtyT1/Casualty_01 as the placeholder visual.
- The three trajectory fields (UntreatedTrajectoryAssetPath,
  TreatedTrajectoryAssetPath, TrajectoryBranchPointSeconds) are for a fallback
  physiology path that is not active. Leave the two strings empty and the number
  0.
- "AuthoringNote" is where you record provenance for the numbers you invented.
  Every clinical value on a row like this is required to be labelled as a
  clinically plausible placeholder with SME validation pending, because no
  clinician has reviewed it.
- "InitialConsciousness01" is a 0..1 reading of how awake the casualty is: 1.0 is
  fully alert and oriented, 0.0 is completely unresponsive.
"""


def build_generator_prompt(request: ArchetypeRequest) -> str:
    """Build the Generator prompt for one request.

    Contains: the exemplar row, the field-group semantics from the schema
    decision record, the clinical brief, and the output contract. Contains no
    SALT rule — see the module docstring.
    """
    return f"""You are a content author on Golden Hour, a VR mass-casualty triage \
trainer built in Unreal Engine 5.8. You author rows for the DataTable \
DT_CasualtyArchetypes. Each row fully describes one casualty archetype: which \
Pulse physiology patient file it starts from, its starting vitals, its bleeding \
insult, and the per-casualty threshold bands the assessment verbs read.

Here is the table as it exists today — the header and the one hand-authored row. \
Match this shape and this style of value exactly:

```csv
{load_exemplar_csv_text()}
```

Here is the field specification these columns come from, taken from the project's \
own schema decision record:

{load_field_group_excerpt()}

---

AUTHOR THIS CASUALTY:

{request.brief}

---

Author the row the way an experienced content author would: picture this \
casualty, choose vitals that fit the clinical picture you have just read, set the \
threshold bands sensibly, and declare in DeclaredCategory which SALT triage \
category you believe this casualty presents as. Use your own clinical judgement \
for the category call.

{_OUTPUT_CONTRACT.format(shape=json_shape())}
"""


def build_refiner_prompt(item: GeneratedArchetype, violations: list[Violation]) -> str:
    """Build the Refiner prompt for one failing item.

    Contains: the failing item as JSON and the violation list. Contains neither
    the derived category nor an instruction naming the correct value — see the
    module docstring.
    """
    # The evaluator's own detail names the derived category, because a human
    # reading the run log needs to see both sides of the disagreement. The
    # refiner must not see it, so it is stripped here — one redaction point,
    # applied to every violation, rather than a rule the caller has to remember.
    safe_violations = redact_violations(violations)

    violation_block = "\n\n".join(
        f"""VIOLATION {i}: {v.code}
Rule: {v.rule}
Authority: {v.gdd_source}
What was found: {v.detail}"""
        for i, v in enumerate(safe_violations, start=1)
    )

    item_json = json.dumps(item.model_dump(mode="json"), indent=2)

    return f"""You are a content author on Golden Hour, a VR mass-casualty triage \
trainer built in Unreal Engine 5.8, revising a casualty archetype row that failed \
review.

Here is the row you submitted:

```json
{item_json}
```

The reviewer raised the following against it. Each one cites the project design \
document that is the authority for the rule:

{violation_block}

Revise the submission so that none of these findings still hold.

You have not been told what the corrected values are, and you should not expect \
to be. Work it out from the row itself: read your own authored numbers, read the \
rule each finding cites, and decide what has to change so the row and the rule \
agree. Sometimes the numbers are right and the declaration is wrong; sometimes \
the declaration is right and the numbers do not support it. Both are legitimate \
ways to resolve a finding — choose the one that keeps this casualty faithful to \
the clinical picture it is meant to portray, and change as little else as \
possible.

{_OUTPUT_CONTRACT.format(shape=json_shape())}
"""
